[10.06.2025 11:58:40,54] Starting Uvicorn... 
INFO:     Will watch for changes in these directories: ['C:\\Users\\camelo.cruz\\Documents\\GitHub\\workflow\\tgt']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [84400] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt-venv\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt-venv\Lib\site-packages\uvicorn\server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt-venv\Lib\site-packages\uvicorn\server.py", line 70, in serve
    await self._serve(sockets)
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt-venv\Lib\site-packages\uvicorn\server.py", line 77, in _serve
    config.load()
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt-venv\Lib\site-packages\uvicorn\config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt-venv\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt\app.py", line 9, in <module>
    from routers.jobs import router as jobs_router
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt\routers\jobs.py", line 19, in <module>
    from inference.api_interface.translate import Translator
  File "C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt\inference\api_interface\translate.py", line 9, in <module>
    from ..translation.factory import TranslationStrategyFactory
ImportError: cannot import name 'TranslationStrategyFactory' from 'inference.translation.factory' (C:\Users\camelo.cruz\Documents\GitHub\workflow\tgt\inference\translation\factory.py)
